# Generated by Django 4.2.19 on 2025-02-19 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('burger_shop', '0006_alter_order_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='BurgerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(max_length=2000, verbose_name='Content')),
                ('burger', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='burger_shop.customburger')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
