# Generated by Django 4.2.19 on 2025-02-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burger_shop', '0007_burgerreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='burgerreview',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0),
            preserve_default=False,
        ),
    ]
