# Generated by Django 4.2.19 on 2025-02-23 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burger_shop', '0009_alter_blogpost_content_alter_burgerreview_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/'),
        ),
    ]
