# Generated by Django 4.2.19 on 2025-02-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burger_shop', '0010_blogpost_content_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burgerreview',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
