# Generated by Django 4.2.19 on 2025-02-23 13:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('burger_shop', '0011_alter_burgerreview_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='customburger',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
