# Generated by Django 4.2.19 on 2025-02-23 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('burger_shop', '0012_customburger_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_status',
        ),
    ]
