# Generated by Django 4.2.19 on 2025-02-25 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('burger_shop', '0013_remove_order_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.PositiveIntegerField(default=0)),
                ('protein', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('fat', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('carbs', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='nutrition',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='burger_shop.nutrition'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='nutrition',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='burger_shop.nutrition'),
        ),
    ]
